---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db

spec:
  containers:
    - name: db-cont
      image: nginx
      ports:
        - containerPort: 80
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
             matchLabels:
               app: frontend
          topologyKey: kubernetes.io/hostname    
