---
apiVersion: v1
kind: Pod
metadata:
  name: logs-pod
  labels:
    app: logs

spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
             matchLabels:
               app: db
          topologyKey: kubernetes.io/hostnamei
